
package DiscUtils.Ntfs;

import java.util.Arrays;
import java.util.EnumSet;
import java.util.stream.Collectors;

public enum AttributeTypeFlags {
    None,
    __dummyEnum__0,
    Indexed,
    __dummyEnum__1,
    Multiple,
    __dummyEnum__2,
    __dummyEnum__3,
    __dummyEnum__4,
    NotZero,
    __dummyEnum__5,
    __dummyEnum__6,
    __dummyEnum__7,
    __dummyEnum__8,
    __dummyEnum__9,
    __dummyEnum__10,
    __dummyEnum__11,
    IndexedUnique,
    __dummyEnum__12,
    __dummyEnum__13,
    __dummyEnum__14,
    __dummyEnum__15,
    __dummyEnum__16,
    __dummyEnum__17,
    __dummyEnum__18,
    __dummyEnum__19,
    __dummyEnum__20,
    __dummyEnum__21,
    __dummyEnum__22,
    __dummyEnum__23,
    __dummyEnum__24,
    __dummyEnum__25,
    __dummyEnum__26,
    NamedUnique,
    __dummyEnum__27,
    __dummyEnum__28,
    __dummyEnum__29,
    __dummyEnum__30,
    __dummyEnum__31,
    __dummyEnum__32,
    __dummyEnum__33,
    __dummyEnum__34,
    __dummyEnum__35,
    __dummyEnum__36,
    __dummyEnum__37,
    __dummyEnum__38,
    __dummyEnum__39,
    __dummyEnum__40,
    __dummyEnum__41,
    __dummyEnum__42,
    __dummyEnum__43,
    __dummyEnum__44,
    __dummyEnum__45,
    __dummyEnum__46,
    __dummyEnum__47,
    __dummyEnum__48,
    __dummyEnum__49,
    __dummyEnum__50,
    __dummyEnum__51,
    __dummyEnum__52,
    __dummyEnum__53,
    __dummyEnum__54,
    __dummyEnum__55,
    __dummyEnum__56,
    __dummyEnum__57,
    MustBeResident,
    __dummyEnum__58,
    __dummyEnum__59,
    __dummyEnum__60,
    __dummyEnum__61,
    __dummyEnum__62,
    __dummyEnum__63,
    __dummyEnum__64,
    __dummyEnum__65,
    __dummyEnum__66,
    __dummyEnum__67,
    __dummyEnum__68,
    __dummyEnum__69,
    __dummyEnum__70,
    __dummyEnum__71,
    __dummyEnum__72,
    __dummyEnum__73,
    __dummyEnum__74,
    __dummyEnum__75,
    __dummyEnum__76,
    __dummyEnum__77,
    __dummyEnum__78,
    __dummyEnum__79,
    __dummyEnum__80,
    __dummyEnum__81,
    __dummyEnum__82,
    __dummyEnum__83,
    __dummyEnum__84,
    __dummyEnum__85,
    __dummyEnum__86,
    __dummyEnum__87,
    __dummyEnum__88,
    __dummyEnum__89,
    __dummyEnum__90,
    __dummyEnum__91,
    __dummyEnum__92,
    __dummyEnum__93,
    __dummyEnum__94,
    __dummyEnum__95,
    __dummyEnum__96,
    __dummyEnum__97,
    __dummyEnum__98,
    __dummyEnum__99,
    __dummyEnum__100,
    __dummyEnum__101,
    __dummyEnum__102,
    __dummyEnum__103,
    __dummyEnum__104,
    __dummyEnum__105,
    __dummyEnum__106,
    __dummyEnum__107,
    __dummyEnum__108,
    __dummyEnum__109,
    __dummyEnum__110,
    __dummyEnum__111,
    __dummyEnum__112,
    __dummyEnum__113,
    __dummyEnum__114,
    __dummyEnum__115,
    __dummyEnum__116,
    __dummyEnum__117,
    __dummyEnum__118,
    __dummyEnum__119,
    __dummyEnum__120,
    CanBeNonResident;

    public static EnumSet<AttributeTypeFlags> valueOf(int value) {
        return Arrays.stream(values())
                .filter(v -> (value & v.ordinal()) != 0)
                .collect(Collectors.toCollection(() -> EnumSet.noneOf(AttributeTypeFlags.class)));
    }

    public static long valueOf(EnumSet<AttributeTypeFlags> flags) {
        return flags.stream().collect(Collectors.summarizingInt(e -> e.ordinal())).getSum();
    }
}
