//
// Copyright (c) 2008-2011, Kenneth Bell
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

package discUtils.diagnostics;

import java.util.ArrayList;
import java.util.List;


/**
 * The report generated by replaying file system actions from a checkpoint.
 * This report contains detailed tracing information.
 */
public final class ReplayReport {

    private final Exception failureException;

    private final Exception replayException;

    private final List<StreamTraceRecord> globalTraceReport;

    private final List<StreamTraceRecord> traceReport;

    private final int replayBufferSize;

    private final int eventsReplayed;

    private final long eventsBeforeLockdown;

    private final String replayPreVerificationReport;

    private final boolean failedVerifyOnReplay;

    private final String replayVerificationReport;

    private final String lastCheckpointReport;

    public ReplayReport(Exception failureEx,
            Exception replayEx,
            TracingStream globalTraceStream,
            TracingStream traceStream,
            int replayBufferSize,
            int eventsReplayed,
            long eventsBeforeLockdown,
            String replayPreVerificationReport,
            boolean failedVerifyOnReplay,
            String replayVerificationReport,
            String lastCheckpointReport) {
        failureException = failureEx;
        replayException = replayEx;
        globalTraceReport = new ArrayList<>(globalTraceStream.getLog());
        traceReport = new ArrayList<>(traceStream.getLog());
        this.replayBufferSize = replayBufferSize;
        this.eventsReplayed = eventsReplayed;
        this.eventsBeforeLockdown = eventsBeforeLockdown;
        this.replayPreVerificationReport = replayPreVerificationReport;
        this.failedVerifyOnReplay = failedVerifyOnReplay;
        this.replayVerificationReport = replayVerificationReport;
        this.lastCheckpointReport = lastCheckpointReport;
    }

    /**
     * The exception (if any) that caused the file system verification check to
     * fail.
     */
    public Exception getVerificationFailureException() {
        return failureException;
    }

    /**
     * The exception (if any) that cause the full replay to fail.
     */
    public Exception getReplayException() {
        return replayException;
    }

    /**
     * The stream activities traced whilst replaying the file system action that
     * broke the file system.
     */
    public List<StreamTraceRecord> getInterCheckpointStreamTraceLog() {
        return globalTraceReport;
    }

    /**
     * The stream activities traced whilst replaying the file system action that
     * broke the file system.
     */
    public List<StreamTraceRecord> getReplayStreamTraceLog() {
        return traceReport;
    }

    /**
     * The number of replay events available to replay.
     */
    public int getReplayEventsAvailable() {
        return replayBufferSize;
    }

    /**
     * The number of replay events successfully replayed.
     */
    public int getReplayEventsProcessed() {
        return eventsReplayed;
    }

    /**
     * Gets whether file system corruption was detected whilst replaying events.
     */
    public boolean getReplayFailedVerification() {
        return failedVerifyOnReplay;
    }

    /**
     * Gets the file system verification report generated at the last
     * checkpoint.
     */
    public String getLastCheckpointReport() {
        return lastCheckpointReport;
    }

    /**
     * Gets the file system verification report generated whilst just before
     * replaying the file system action that failed.
     */
    public String getReplayPreVerificationReport() {
        return replayPreVerificationReport;
    }

    /**
     * Gets the file system verification report generated whilst replaying the
     * file system action that failed.
     */
    public String getReplayVerificationReport() {
        return replayVerificationReport;
    }

    /**
     * The total number of events processed (ignoring events run during replay).
     */
    public long getTotalEventsProcessed() {
        return eventsBeforeLockdown;
    }
}
